# runtime: python37
# # entrypoint: gunicorn main:app --log-file=-
# # entrypoint: gunicorn -b :$PORT main:app
# entrypoint: gunicorn --bind=8080:5000 main:app --log-file=-

runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3
